[MODEL]
OUT_FEATURES=[32, 8]
NUM_CLASSES=2
DATASET=UNSW_NB15
; SELECTED_FEATURES=[
;     "sttl",
;     "ct_srv_dst", 
;     "ct_dst_src_ltm", 
;     "ct_srv_src", 
;     "sbytes", 
;     "smean", 
;     "synack", 
;     "dmean", 
;     "tcprtt", 
;     "ct_src_ltm", 
;     "dbytes",
;     "service", 
;     "ct_dst_sport_ltm", 
;     "dloss", 
;     "dload", 
;     "ct_dst_ltm", 
;     "sloss", 
;     "swin", 
;     "label"
;     ]
SELECTED_FEATURES= [
    "sbytes",
    "dbytes",
    "sttl",
    "dttl",
    "spkts",
    "dpkts",
    "smean",
    "dmean",
    "synack",
    "ackdat",
    "tcprtt",
    "label"]
[QUANT]
WEIGHT_BIT_WIDTH=1
ACT_BIT_WIDTH=1
IN_BIT_WIDTH=1