[TRAINING]
FOLDS=5
BATCH_SIZE=2048
SUBSET_SIZE=
LOSS=SqrHinge
OPTIM=ADAM
SCHEDULER=FIXED
LR=5e-4
MOMENTUM=0.9
WEIGHT_DECAY=1e-3
DISTILLED=False
LOG_FREQ=10
RANDOM_SEED=42
EXTR_FEATS_WIDTH=168

MLP_MODEL_EPOCHS=10

; debug
; MLP_MODEL_EPOCHS=3


; debug
; BNN_CROSS_VAL_EPOCHS=3
; BNN_FINAL_EPOCHS=4

; CICIDS2017
BNN_CROSS_VAL_EPOCHS=25
BNN_FINAL_EPOCHS=30

; UNSW-NB15
; BNN_CROSS_VAL_EPOCHS=170
; BNN_FINAL_EPOCHS=180

; CIC-UNSW-NB15
; BNN_CROSS_VAL_EPOCHS=110
; BNN_FINAL_EPOCHS=120

[SHAP]
SHAP_PATH=/home/sgeraci/inet-hynn/p4src/shaps
; BACKGROUND_SIZE=256
; EXPLAIN_SIZE=512

; debug
BACKGROUND_SIZE=32
EXPLAIN_SIZE=128