; ----------------------------------------
; Distribution Shift Retraining Settings
; ----------------------------------------
[DS_RETRAINING]
MAX_UNSW_FRACTION = 0.4
DATASET_SWITCH_START = 20
DATASET_SWITCH_END = 40
BATCH_SIZE = 1200
N_BATCHES = 170

[DS_RETRAINING-BINOCULAR_TINY]
CRITICAL_RETRAIN_SAMPLES = 20000
EMPIRICAL_RETRAIN_SAMPLES = 40000
OG_RETRAIN_SAMPLES = 800000
RETRAINING_EPOCHS = 50

[DS_RETRAINING-BINOCULAR_DENSE]
CRITICAL_RETRAIN_SAMPLES = 40000
EMPIRICAL_RETRAIN_SAMPLES = 60000
OG_RETRAIN_SAMPLES = 800000
RETRAINING_EPOCHS = 50

[DS_RETRAINING-BINOCULAR_WIDE]
CRITICAL_RETRAIN_SAMPLES = 10000
EMPIRICAL_RETRAIN_SAMPLES = 62000
OG_RETRAIN_SAMPLES = 800000
RETRAINING_EPOCHS = 50

; ----------------------------------------
; Distribution Shift Without Retraining Settings (other paper comparison)
; ----------------------------------------
[DS_NO_RETRAINING]
MAX_UNSW_FRACTION = 0.4
DATASET_SWITCH_START = 20
DATASET_SWITCH_END = 40
BATCH_SIZE = 1200
N_BATCHES = 170