[DATASET]
name=UNSW-NB15-custom

SELECTED_FEATURES= [
    "proto",
    "sbytes", 
    "dbytes", 
    ; "sttl", 
    ; "dttl", 
    "spkts", 
    "dpkts", 
    "smeansz", 
    "dmeansz",
    ; "synack", 
    ; "ackdat",
    "smaxbytes", 
    "dmaxbytes", 
    "sminbytes", 
    "dminbytes", 
    ; "minbytes", 
    ; "maxbytes",
    "fin_cnt", 
    "syn_cnt", 
    "ack_cnt", 
    "psh_cnt", 
    "rst_cnt", 
    "ece_cnt",
    ; "iat_mean", 
    ; "iat_std", 
    ; "iat_min", 
    ; "iat_max",
    ; "stime", 
    ; "ltime",
    "attack_cat",
    "label"]

PATH=/home/sgeraci/Desktop/datasets/UNSW-NB15-custom/unswnb15_custom.csv